// <auto-generated />
using System;
using CH_BACKEND.DBCalzadosHuancayo;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CH_BACKEND.Migrations
{
    [DbContext(typeof(_DbContextCalzadosHuancayo))]
    [Migration("20250730013109_RemoveMarcaFromProducto")]
    partial class RemoveMarcaFromProducto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CH_BACKEND.DBCalzadosHuancayo.Carrito", b =>
                {
                    b.Property<int>("IdCarrito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_carrito");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCarrito"));

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.HasKey("IdCarrito")
                        .HasName("PK__Carrito__83A2AD9C69CB431D");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Carrito");
                });

            modelBuilder.Entity("CH_BACKEND.DBCalzadosHuancayo.CarritoDetalle", b =>
                {
                    b.Property<int>("IdCarrito")
                        .HasColumnType("int")
                        .HasColumnName("id_carrito")
                        .HasColumnOrder(0);

                    b.Property<int>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("id_producto")
                        .HasColumnOrder(1);

                    b.Property<int>("IdTalla")
                        .HasColumnType("int")
                        .HasColumnName("id_talla")
                        .HasColumnOrder(2);

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(8, 2)")
                        .HasColumnName("cantidad");

                    b.HasKey("IdCarrito", "IdProducto", "IdTalla")
                        .HasName("PK__Carrito___7090831C4615DB4B");

                    b.HasIndex("IdProducto");

                    b.ToTable("Carrito_Detalle");
                });

            modelBuilder.Entity("CH_BACKEND.DBCalzadosHuancayo.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_categoria");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("descripcion");

                    b.HasKey("IdCategoria")
                        .HasName("PK__Categori__CD54BC5A95EA531F");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("CH_BACKEND.DBCalzadosHuancayo.DetalleVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(8, 2)")
                        .HasColumnName("cantidad");

                    b.Property<decimal?>("Descuento")
                        .HasColumnType("decimal(8, 2)")
                        .HasColumnName("descuento");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    b.Property<int?>("IdUnidadMedida")
                        .HasColumnType("int")
                        .HasColumnName("id_unidad_medida");

                    b.Property<int>("IdVenta")
                        .HasColumnType("int")
                        .HasColumnName("id_venta");

                    b.Property<decimal?>("Igv")
                        .HasColumnType("decimal(8, 2)")
                        .HasColumnName("igv");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(8, 2)")
                        .HasColumnName("precio");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(8, 2)")
                        .HasColumnName("total");

                    b.HasKey("Id")
                        .HasName("PK__DetalleV__3213E83FB2E9106F");

                    b.HasIndex("IdProducto");

                    b.HasIndex("IdUnidadMedida");

                    b.HasIndex("IdVenta");

                    b.ToTable("DetalleVenta");
                });

            modelBuilder.Entity("CH_BACKEND.DBCalzadosHuancayo.Devolucion", b =>
                {
                    b.Property<int>("IdDevolucion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_devolucion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDevolucion"));

                    b.Property<decimal>("CantidadDevolucion")
                        .HasColumnType("decimal(8, 2)")
                        .HasColumnName("cantidad_devolucion");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    b.Property<int>("IdVenta")
                        .HasColumnType("int")
                        .HasColumnName("id_venta");

                    b.Property<string>("Motivo")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("motivo");

                    b.HasKey("IdDevolucion")
                        .HasName("PK__Devoluci__0BBAEF8D371B6290");

                    b.HasIndex("IdProducto");

                    b.HasIndex("IdVenta");

                    b.ToTable("Devoluciones");
                });

            modelBuilder.Entity("CH_BACKEND.DBCalzadosHuancayo.DireccionEntrega", b =>
                {
                    b.Property<int>("IdDireccionEntrega")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_direccion_entrega");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDireccionEntrega"));

                    b.Property<decimal>("CostoEnvio")
                        .HasColumnType("decimal(8, 2)")
                        .HasColumnName("costo_envio");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("direccion");

                    b.Property<int>("IdVenta")
                        .HasColumnType("int")
                        .HasColumnName("id_venta");

                    b.Property<decimal?>("Lat")
                        .HasColumnType("decimal(9, 6)")
                        .HasColumnName("lat");

                    b.Property<decimal?>("Lng")
                        .HasColumnType("decimal(9, 6)")
                        .HasColumnName("lng");

                    b.Property<string>("Referencia")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("referencia");

                    b.HasKey("IdDireccionEntrega")
                        .HasName("PK__Direccio__EA452087DE9D7120");

                    b.HasIndex("IdVenta");

                    b.ToTable("DireccionEntrega");
                });

            modelBuilder.Entity("CH_BACKEND.DBCalzadosHuancayo.Empresa", b =>
                {
                    b.Property<int>("IdEmpresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_empresa");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmpresa"));

                    b.Property<string>("Correo")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("correo");

                    b.Property<string>("Direccion")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("direccion");

                    b.Property<string>("NombreEmpresa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre_empresa");

                    b.Property<string>("Ruc")
                        .IsRequired()
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("ruc");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefono");

                    b.HasKey("IdEmpresa")
                        .HasName("PK__Empresa__4A0B7E2C00D3FFD2");

                    b.ToTable("Empresa");
                });

            modelBuilder.Entity("CH_BACKEND.DBCalzadosHuancayo.HistorialInventario", b =>
                {
                    b.Property<int>("IdMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_movimiento");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMovimiento"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(8, 2)")
                        .HasColumnName("cantidad");

                    b.Property<DateOnly?>("CompraFecha")
                        .HasColumnType("date")
                        .HasColumnName("compra_fecha");

                    b.Property<decimal?>("CompraTotal")
                        .HasColumnType("decimal(8, 2)")
                        .HasColumnName("compra_total");

                    b.Property<string>("DocumentoCompra")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("documento_compra");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    b.Property<int?>("IdProveedor")
                        .HasColumnType("int")
                        .HasColumnName("id_proveedor");

                    b.Property<string>("ProveedorContacto")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("proveedor_contacto");

                    b.Property<string>("ProveedorNombre")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("proveedor_nombre");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("tipo_movimiento");

                    b.Property<int?>("UsuarioResponsable")
                        .HasColumnType("int")
                        .HasColumnName("usuario_responsable");

                    b.HasKey("IdMovimiento")
                        .HasName("PK__Historia__2A071C24B44D7A36");

                    b.HasIndex("IdProducto");

                    b.HasIndex("UsuarioResponsable");

                    b.ToTable("HistorialInventario");
                });

            modelBuilder.Entity("CH_BACKEND.DBCalzadosHuancayo.Inventario", b =>
                {
                    b.Property<int>("IdInventario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_inventario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdInventario"));

                    b.Property<decimal>("CantidadInventario")
                        .HasColumnType("decimal(8, 2)")
                        .HasColumnName("cantidad_inventario");

                    b.Property<DateOnly>("FechaRegistro")
                        .HasColumnType("date")
                        .HasColumnName("fecha_registro");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("tipo_movimiento");

                    b.HasKey("IdInventario")
                        .HasName("PK__Inventar__013AEB511DD5E6B9");

                    b.HasIndex("IdProducto");

                    b.ToTable("Inventario");
                });

            modelBuilder.Entity("CH_BACKEND.DBCalzadosHuancayo.MedioPago", b =>
                {
                    b.Property<int>("IdMedioPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_medio_pago");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMedioPago"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Titular")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("titular");

                    b.HasKey("IdMedioPago")
                        .HasName("PK__MedioPag__19467AD5802A4AB8");

                    b.ToTable("MedioPago");
                });

            modelBuilder.Entity("CH_BACKEND.DBCalzadosHuancayo.Pago", b =>
                {
                    b.Property<int>("IdPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_pago");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPago"));

                    b.Property<string>("ComprobanteUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("comprobante_url");

                    b.Property<string>("EstadoPago")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("estado_pago");

                    b.Property<DateOnly>("FechaPago")
                        .HasColumnType("date")
                        .HasColumnName("fecha_pago");

                    b.Property<int?>("IdMedioPago")
                        .HasColumnType("int")
                        .HasColumnName("id_medio_pago");

                    b.Property<string>("IdTransaccionMP")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("id_transaccion_mp");

                    b.Property<int>("IdVenta")
                        .HasColumnType("int")
                        .HasColumnName("id_venta");

                    b.Property<decimal>("MontoPagado")
                        .HasColumnType("decimal(8, 2)")
                        .HasColumnName("monto_pagado");

                    b.Property<string>("PreferenceIdMP")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("preference_id_mp");

                    b.HasKey("IdPago")
                        .HasName("PK__Pago__0941B074510023E3");

                    b.HasIndex("IdVenta");

                    b.ToTable("Pago");
                });

            modelBuilder.Entity("CH_BACKEND.DBCalzadosHuancayo.Persona", b =>
                {
                    b.Property<int>("IdPersona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPersona"));

                    b.Property<string>("Correo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NumeroDocumento")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("numero_documento");

                    b.Property<string>("Telefono")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TipoDocumento")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tipo_documento");

                    b.Property<string>("TipoPersona")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Cliente");

                    b.HasKey("IdPersona")
                        .HasName("PK__Persona__2EC8D2ACBFB74037");

                    b.ToTable("Persona");
                });

            modelBuilder.Entity("CH_BACKEND.DBCalzadosHuancayo.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProducto"));

                    b.Property<string>("Articulo")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("articulo");

                    b.Property<string>("CodigoBarra")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("codigo_barra");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Color");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit")
                        .HasColumnName("estado");

                    b.Property<string>("Estilo")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("estilo");

                    b.Property<string>("Foto")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("foto");

                    b.Property<string>("Genero")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("genero");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int")
                        .HasColumnName("id_categoria");

                    b.Property<int?>("IdSubCategoria")
                        .HasColumnType("int")
                        .HasColumnName("id_sub_categoria");

                    b.Property<int>("IdUnidadMedida")
                        .HasColumnType("int")
                        .HasColumnName("id_unidad_medida");

                    b.Property<string>("Marca")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("marca");

                    b.Property<string>("Material")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Material");

                    b.Property<string>("Mpn")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Mpn");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.Property<decimal?>("PrecioCompra")
                        .HasColumnType("decimal(8, 2)")
                        .HasColumnName("precio_compra");

                    b.Property<decimal>("PrecioVenta")
                        .HasColumnType("decimal(8, 2)")
                        .HasColumnName("precio_venta");

                    b.Property<string>("ShippingInfo")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("ShippingInfo");

                    b.Property<decimal>("Stock")
                        .HasColumnType("decimal(8, 2)")
                        .HasColumnName("stock");

                    b.Property<decimal>("StockMinimo")
                        .HasColumnType("decimal(8, 2)")
                        .HasColumnName("stock_minimo");

                    b.HasKey("IdProducto")
                        .HasName("PK__Producto__FF341C0D54E1F0E5");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdSubCategoria");

                    b.HasIndex("IdUnidadMedida");

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("CH_BACKEND.DBCalzadosHuancayo.Promocion", b =>
                {
                    b.Property<int>("IdPromocion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_promocion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPromocion"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("descripcion");

                    b.Property<decimal>("Descuento")
                        .HasColumnType("decimal(8, 2)")
                        .HasColumnName("descuento");

                    b.Property<DateOnly>("FechaFin")
                        .HasColumnType("date")
                        .HasColumnName("fecha_fin");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date")
                        .HasColumnName("fecha_inicio");

                    b.Property<string>("TipoDescuento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("tipo_descuento");

                    b.HasKey("IdPromocion")
                        .HasName("PK__Promocio__F89308E0881B49D8");

                    b.ToTable("Promocion");
                });

            modelBuilder.Entity("CH_BACKEND.DBCalzadosHuancayo.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("IdRol")
                        .HasName("PK__Rol__6ABCB5E05CD9B680");

                    b.ToTable("Rol");
                });

            modelBuilder.Entity("CH_BACKEND.DBCalzadosHuancayo.SubCategoria", b =>
                {
                    b.Property<int>("IdSubCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_sub_categoria");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSubCategoria"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("descripcion");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int")
                        .HasColumnName("id_categoria");

                    b.HasKey("IdSubCategoria")
                        .HasName("PK__SubCateg__52A25E8A2A196AFE");

                    b.HasIndex("IdCategoria");

                    b.ToTable("SubCategoria");
                });

            modelBuilder.Entity("CH_BACKEND.DBCalzadosHuancayo.Talla", b =>
                {
                    b.Property<int>("IdTalla")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_talla");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTalla"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("categoria");

                    b.Property<decimal>("Cm")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("cm");

                    b.Property<int>("Eur")
                        .HasColumnType("int")
                        .HasColumnName("eur");

                    b.Property<int>("Usa")
                        .HasColumnType("int")
                        .HasColumnName("usa");

                    b.HasKey("IdTalla")
                        .HasName("PK__Talla__C16F403DA58B752D");

                    b.ToTable("Talla");
                });

            modelBuilder.Entity("CH_BACKEND.DBCalzadosHuancayo.TallaProducto", b =>
                {
                    b.Property<int>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("id_producto")
                        .HasColumnOrder(0);

                    b.Property<int>("Usa")
                        .HasColumnType("int")
                        .HasColumnName("usa")
                        .HasColumnOrder(1);

                    b.Property<decimal>("Cm")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("cm");

                    b.Property<int>("Eur")
                        .HasColumnType("int")
                        .HasColumnName("eur");

                    b.Property<decimal>("Stock")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("stock");

                    b.HasKey("IdProducto", "Usa")
                        .HasName("PK_TallaProducto");

                    b.ToTable("Talla_Producto");
                });

            modelBuilder.Entity("CH_BACKEND.DBCalzadosHuancayo.UnidadMedida", b =>
                {
                    b.Property<int>("IdUnidadMedida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_unidad_medida");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUnidadMedida"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("descripcion");

                    b.HasKey("IdUnidadMedida")
                        .HasName("PK__UnidadMe__2F721BD3014DED1B");

                    b.ToTable("UnidadMedida");
                });

            modelBuilder.Entity("CH_BACKEND.DBCalzadosHuancayo.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_registro");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefono");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("username");

                    b.HasKey("IdUsuario")
                        .HasName("PK__Usuario__4E3E04AD691DD7B6");

                    b.HasIndex(new[] { "Username" }, "UQ__Usuario__F3DBC5723454555F")
                        .IsUnique();

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("CH_BACKEND.DBCalzadosHuancayo.UsuarioDireccion", b =>
                {
                    b.Property<int>("IdDireccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_direccion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDireccion"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("direccion");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_registro")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<decimal?>("Lat")
                        .HasColumnType("decimal(9, 6)")
                        .HasColumnName("lat");

                    b.Property<decimal?>("Lng")
                        .HasColumnType("decimal(9, 6)")
                        .HasColumnName("lng");

                    b.Property<string>("Referencia")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("referencia");

                    b.HasKey("IdDireccion")
                        .HasName("PK__UsuarioD__25C35D073F491800");

                    b.HasIndex("IdUsuario");

                    b.ToTable("UsuarioDireccion");
                });

            modelBuilder.Entity("CH_BACKEND.DBCalzadosHuancayo.UsuarioRol", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<int>("IdRol")
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    b.Property<DateOnly>("FechaAsignacion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_asignacion");

                    b.HasKey("IdUsuario", "IdRol")
                        .HasName("PK__Usuario___5895CFF3A0ACAA9D");

                    b.HasIndex("IdRol");

                    b.ToTable("Usuario_Rol");
                });

            modelBuilder.Entity("CH_BACKEND.DBCalzadosHuancayo.Venta", b =>
                {
                    b.Property<int>("IdVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVenta"));

                    b.Property<decimal>("CostoEnvio")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("costo_envio");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EstadoPago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("MetodoEntrega")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("metodo_entrega");

                    b.Property<string>("NumeroComprobante")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Serie")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SucursalRecoge")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("sucursal_recoge");

                    b.Property<string>("TipoComprobante")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalIgv")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_igv");

                    b.HasKey("IdVenta")
                        .HasName("PK__Venta__BC1240BD26422425");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Venta", (string)null);
                });

            modelBuilder.Entity("CH_BACKEND.DBCalzadosHuancayo.VentaEstadoHistorial", b =>
                {
                    b.Property<int>("IdHistorial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_historial");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHistorial"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCambio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_cambio")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdVenta")
                        .HasColumnType("int")
                        .HasColumnName("id_venta");

                    b.HasKey("IdHistorial")
                        .HasName("PK__VentaEst__76E6C5029544A030");

                    b.HasIndex("IdVenta");

                    b.ToTable("VentaEstadoHistorial");
                });

            modelBuilder.Entity("ProductoPromocion", b =>
                {
                    b.Property<int>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    b.Property<int>("IdPromocion")
                        .HasColumnType("int")
                        .HasColumnName("id_promocion");

                    b.HasKey("IdProducto", "IdPromocion")
                        .HasName("PK__Producto__E0BD2C8374DEB058");

                    b.HasIndex("IdPromocion");

                    b.ToTable("Producto_Promocion", (string)null);
                });

            modelBuilder.Entity("CH_BACKEND.DBCalzadosHuancayo.Carrito", b =>
                {
                    b.HasOne("CH_BACKEND.DBCalzadosHuancayo.Usuario", "IdUsuarioNavigation")
                        .WithMany("Carritos")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK_Carrito_Usuario");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("CH_BACKEND.DBCalzadosHuancayo.CarritoDetalle", b =>
                {
                    b.HasOne("CH_BACKEND.DBCalzadosHuancayo.Carrito", "IdCarritoNavigation")
                        .WithMany("CarritoDetalles")
                        .HasForeignKey("IdCarrito")
                        .IsRequired()
                        .HasConstraintName("FK_CarritoDetalle_Carrito");

                    b.HasOne("CH_BACKEND.DBCalzadosHuancayo.Producto", "IdProductoNavigation")
                        .WithMany("CarritoDetalles")
                        .HasForeignKey("IdProducto")
                        .IsRequired()
                        .HasConstraintName("FK_CarritoDetalle_Producto");

                    b.Navigation("IdCarritoNavigation");

                    b.Navigation("IdProductoNavigation");
                });

            modelBuilder.Entity("CH_BACKEND.DBCalzadosHuancayo.DetalleVenta", b =>
                {
                    b.HasOne("CH_BACKEND.DBCalzadosHuancayo.Producto", "IdProductoNavigation")
                        .WithMany("DetalleVenta")
                        .HasForeignKey("IdProducto")
                        .IsRequired()
                        .HasConstraintName("FK__DetalleVe__id_pr__6477ECF3");

                    b.HasOne("CH_BACKEND.DBCalzadosHuancayo.UnidadMedida", "IdUnidadMedidaNavigation")
                        .WithMany("DetalleVenta")
                        .HasForeignKey("IdUnidadMedida")
                        .HasConstraintName("FK__DetalleVe__id_un__656C112C");

                    b.HasOne("CH_BACKEND.DBCalzadosHuancayo.Venta", "IdVentaNavigation")
                        .WithMany("DetalleVenta")
                        .HasForeignKey("IdVenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__DetalleVe__id_ve__6383C8BA");

                    b.Navigation("IdProductoNavigation");

                    b.Navigation("IdUnidadMedidaNavigation");

                    b.Navigation("IdVentaNavigation");
                });

            modelBuilder.Entity("CH_BACKEND.DBCalzadosHuancayo.Devolucion", b =>
                {
                    b.HasOne("CH_BACKEND.DBCalzadosHuancayo.Producto", "IdProductoNavigation")
                        .WithMany("Devoluciones")
                        .HasForeignKey("IdProducto")
                        .IsRequired()
                        .HasConstraintName("FK__Devolucio__id_pr__6EF57B66");

                    b.HasOne("CH_BACKEND.DBCalzadosHuancayo.Venta", "IdVentaNavigation")
                        .WithMany("Devoluciones")
                        .HasForeignKey("IdVenta")
                        .IsRequired()
                        .HasConstraintName("FK__Devolucio__id_ve__6E01572D");

                    b.Navigation("IdProductoNavigation");

                    b.Navigation("IdVentaNavigation");
                });

            modelBuilder.Entity("CH_BACKEND.DBCalzadosHuancayo.DireccionEntrega", b =>
                {
                    b.HasOne("CH_BACKEND.DBCalzadosHuancayo.Venta", "IdVentaNavigation")
                        .WithMany("DireccionEntregas")
                        .HasForeignKey("IdVenta")
                        .IsRequired()
                        .HasConstraintName("FK_DireccionEntrega_Venta");

                    b.Navigation("IdVentaNavigation");
                });

            modelBuilder.Entity("CH_BACKEND.DBCalzadosHuancayo.HistorialInventario", b =>
                {
                    b.HasOne("CH_BACKEND.DBCalzadosHuancayo.Producto", "IdProductoNavigation")
                        .WithMany("HistorialInventarios")
                        .HasForeignKey("IdProducto")
                        .IsRequired()
                        .HasConstraintName("FK__Historial__id_pr__02084FDA");

                    b.HasOne("CH_BACKEND.DBCalzadosHuancayo.Usuario", "UsuarioResponsableNavigation")
                        .WithMany("HistorialInventarios")
                        .HasForeignKey("UsuarioResponsable")
                        .HasConstraintName("FK__Historial__usuar__02FC7413");

                    b.Navigation("IdProductoNavigation");

                    b.Navigation("UsuarioResponsableNavigation");
                });

            modelBuilder.Entity("CH_BACKEND.DBCalzadosHuancayo.Inventario", b =>
                {
                    b.HasOne("CH_BACKEND.DBCalzadosHuancayo.Producto", "IdProductoNavigation")
                        .WithMany("Inventarios")
                        .HasForeignKey("IdProducto")
                        .IsRequired()
                        .HasConstraintName("FK__Inventari__id_pr__71D1E811");

                    b.Navigation("IdProductoNavigation");
                });

            modelBuilder.Entity("CH_BACKEND.DBCalzadosHuancayo.Pago", b =>
                {
                    b.HasOne("CH_BACKEND.DBCalzadosHuancayo.Venta", "IdVentaNavigation")
                        .WithMany("Pagos")
                        .HasForeignKey("IdVenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Pago__id_venta__6A30C649");

                    b.Navigation("IdVentaNavigation");
                });

            modelBuilder.Entity("CH_BACKEND.DBCalzadosHuancayo.Producto", b =>
                {
                    b.HasOne("CH_BACKEND.DBCalzadosHuancayo.Categoria", "IdCategoriaNavigation")
                        .WithMany("Productos")
                        .HasForeignKey("IdCategoria")
                        .IsRequired()
                        .HasConstraintName("FK__Producto__id_cat__5070F446");

                    b.HasOne("CH_BACKEND.DBCalzadosHuancayo.SubCategoria", "IdSubCategoriaNavigation")
                        .WithMany("Productos")
                        .HasForeignKey("IdSubCategoria")
                        .HasConstraintName("FK__Producto__id_sub__5165187F");

                    b.HasOne("CH_BACKEND.DBCalzadosHuancayo.UnidadMedida", "IdUnidadMedidaNavigation")
                        .WithMany("Productos")
                        .HasForeignKey("IdUnidadMedida")
                        .IsRequired()
                        .HasConstraintName("FK__Producto__id_uni__52593CB8");

                    b.Navigation("IdCategoriaNavigation");

                    b.Navigation("IdSubCategoriaNavigation");

                    b.Navigation("IdUnidadMedidaNavigation");
                });

            modelBuilder.Entity("CH_BACKEND.DBCalzadosHuancayo.SubCategoria", b =>
                {
                    b.HasOne("CH_BACKEND.DBCalzadosHuancayo.Categoria", "IdCategoriaNavigation")
                        .WithMany("SubCategoria")
                        .HasForeignKey("IdCategoria")
                        .IsRequired()
                        .HasConstraintName("FK__SubCatego__id_ca__4BAC3F29");

                    b.Navigation("IdCategoriaNavigation");
                });

            modelBuilder.Entity("CH_BACKEND.DBCalzadosHuancayo.TallaProducto", b =>
                {
                    b.HasOne("CH_BACKEND.DBCalzadosHuancayo.Producto", "IdProductoNavigation")
                        .WithMany("TallaProductos")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TallaProducto_Producto");

                    b.Navigation("IdProductoNavigation");
                });

            modelBuilder.Entity("CH_BACKEND.DBCalzadosHuancayo.UsuarioDireccion", b =>
                {
                    b.HasOne("CH_BACKEND.DBCalzadosHuancayo.Usuario", "IdUsuarioNavigation")
                        .WithMany("UsuarioDireccions")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK_UsuarioDireccion_Usuario");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("CH_BACKEND.DBCalzadosHuancayo.UsuarioRol", b =>
                {
                    b.HasOne("CH_BACKEND.DBCalzadosHuancayo.Rol", "IdRolNavigation")
                        .WithMany("UsuarioRols")
                        .HasForeignKey("IdRol")
                        .IsRequired()
                        .HasConstraintName("FK__Usuario_R__id_ro__5DCAEF64");

                    b.HasOne("CH_BACKEND.DBCalzadosHuancayo.Usuario", "IdUsuarioNavigation")
                        .WithMany("UsuarioRols")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK__Usuario_R__id_us__5CD6CB2B");

                    b.Navigation("IdRolNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("CH_BACKEND.DBCalzadosHuancayo.Venta", b =>
                {
                    b.HasOne("CH_BACKEND.DBCalzadosHuancayo.Usuario", "IdUsuarioNavigation")
                        .WithMany("Ventas")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK_Venta_Usuario");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("CH_BACKEND.DBCalzadosHuancayo.VentaEstadoHistorial", b =>
                {
                    b.HasOne("CH_BACKEND.DBCalzadosHuancayo.Venta", "IdVentaNavigation")
                        .WithMany("VentaEstadoHistorials")
                        .HasForeignKey("IdVenta")
                        .IsRequired()
                        .HasConstraintName("FK_VentaEstadoHistorial_Venta");

                    b.Navigation("IdVentaNavigation");
                });

            modelBuilder.Entity("ProductoPromocion", b =>
                {
                    b.HasOne("CH_BACKEND.DBCalzadosHuancayo.Producto", null)
                        .WithMany()
                        .HasForeignKey("IdProducto")
                        .IsRequired()
                        .HasConstraintName("FK__Producto___id_pr__76969D2E");

                    b.HasOne("CH_BACKEND.DBCalzadosHuancayo.Promocion", null)
                        .WithMany()
                        .HasForeignKey("IdPromocion")
                        .IsRequired()
                        .HasConstraintName("FK__Producto___id_pr__778AC167");
                });

            modelBuilder.Entity("CH_BACKEND.DBCalzadosHuancayo.Carrito", b =>
                {
                    b.Navigation("CarritoDetalles");
                });

            modelBuilder.Entity("CH_BACKEND.DBCalzadosHuancayo.Categoria", b =>
                {
                    b.Navigation("Productos");

                    b.Navigation("SubCategoria");
                });

            modelBuilder.Entity("CH_BACKEND.DBCalzadosHuancayo.Producto", b =>
                {
                    b.Navigation("CarritoDetalles");

                    b.Navigation("DetalleVenta");

                    b.Navigation("Devoluciones");

                    b.Navigation("HistorialInventarios");

                    b.Navigation("Inventarios");

                    b.Navigation("TallaProductos");
                });

            modelBuilder.Entity("CH_BACKEND.DBCalzadosHuancayo.Rol", b =>
                {
                    b.Navigation("UsuarioRols");
                });

            modelBuilder.Entity("CH_BACKEND.DBCalzadosHuancayo.SubCategoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("CH_BACKEND.DBCalzadosHuancayo.UnidadMedida", b =>
                {
                    b.Navigation("DetalleVenta");

                    b.Navigation("Productos");
                });

            modelBuilder.Entity("CH_BACKEND.DBCalzadosHuancayo.Usuario", b =>
                {
                    b.Navigation("Carritos");

                    b.Navigation("HistorialInventarios");

                    b.Navigation("UsuarioDireccions");

                    b.Navigation("UsuarioRols");

                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("CH_BACKEND.DBCalzadosHuancayo.Venta", b =>
                {
                    b.Navigation("DetalleVenta");

                    b.Navigation("Devoluciones");

                    b.Navigation("DireccionEntregas");

                    b.Navigation("Pagos");

                    b.Navigation("VentaEstadoHistorials");
                });
#pragma warning restore 612, 618
        }
    }
}
